### PR TITLE
Disable @ConstructorProperties From Lombok Generation

### PR DESCRIPTION
**Pull request by brianwyka**
* Change the deserialization to use builder pattern rather than `@ConstructorProperties`
* In Java9+ this has a benefit of removing dependency on `java.base` module

This is a predecessor to #42

### CODE REVIEW

**Comment by brianwyka** [comment]
@amyschoen, not sure why, but the `license/cla` check has not been working recently...

**Review by ctoestreich — APPROVED** [review]

**Comment by amyschoen** [comment]
I'll take a look this afternoon @brianwyka.  Do you know when it stopped working?  I'm wondering if Kevin originally set it up with his account, and I removed his account as org owner when he left the company.

**Comment by brianwyka** [comment]
Most likely correlated @amyschoen.  I can't be 100% certain, though since we had some inactivity after that milestone.

**Comment by amyschoen** [comment]
It was correlated @brianwyka.  This should be working again.  Please let me know if you see any further issues.  I had to completely delete what Kevin originally set up and create a new set up from scratch, so there is the chance that contributors might have to sign again.

**Pull request merged**
